wget https://s3.amazonaws.com/ava-dataset/trainval/_eBah6c5kyA.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/g1wyIcLPbq0.mp4
wget https://s3.amazonaws.com/ava-dataset/trainval/kMy-6RtoOVU.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/KWoSGtglCms.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/l2XO3tQk8lI.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/Lg1jOu8cUBM.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/o4xQ-BEa3Ss.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/oITFHwzfw_k.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/LIavUJVrXaI.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/lT1zdTL-3SM.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/qBUu7cy-5Iw.mp4
wget https://s3.amazonaws.com/ava-dataset/trainval/QCLQYnt3aMo.webm
wget https://s3.amazonaws.com/ava-dataset/trainval/qsTqtWVVSLM.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/qx2vAO5ofmo.mp4
wget https://s3.amazonaws.com/ava-dataset/trainval/rCb9-U4TArw.mp4
wget https://s3.amazonaws.com/ava-dataset/trainval/tjqCzVjojCo.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/tt0t_a1EDCE.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/TzaVHtLXOzY.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/u1ltv6r14KQ.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/UgZFdrNT6W0.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/UIy730JrFIc.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/uNT6HrrnqPU.webm
wget https://s3.amazonaws.com/ava-dataset/trainval/UOfuzrwkclM.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/UOyyTUX5Vo4.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/uPJPNPbWMFk.mp4
wget https://s3.amazonaws.com/ava-dataset/trainval/UrsCy6qIGoo.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/UsLnxI_zGpY.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/uwW0ejeosmk.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/U_WzY2k8IBM.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/uzPI7FcF79U.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/v0L-WkMO3s4.mp4
wget https://s3.amazonaws.com/ava-dataset/trainval/vBbjA4tWCPg.mp4
wget https://s3.amazonaws.com/ava-dataset/trainval/vfjywN5CN0Y.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/Vmef_8MY46w.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/VMNmRlhFT-o.mp4
wget https://s3.amazonaws.com/ava-dataset/trainval/WlgxRNCHQzw.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/wogRuPNBUi8.mp4
wget https://s3.amazonaws.com/ava-dataset/trainval/wONG7Vh87B4.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/WSPvfxtqisg.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/WVde9pyaHg4.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/x-6CtPWVi6E.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/xeGWXqSvC-8.webm
wget https://s3.amazonaws.com/ava-dataset/trainval/XF87VL5T0aA.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/XglAvHaEtHY.mp4
wget https://s3.amazonaws.com/ava-dataset/trainval/xJmRNZVDDCY.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/xmqSaQPzL1E.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/xO4ABy2iOQA.mp4
wget https://s3.amazonaws.com/ava-dataset/trainval/xp67EC-Hvwk.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/z-fsLpGHq6o.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/zG7mx8KiavA.mp4
wget https://s3.amazonaws.com/ava-dataset/trainval/zlVkeKC6Ha8.mp4
wget https://s3.amazonaws.com/ava-dataset/trainval/ZosVdkY76FU.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/zR725veL-DI.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/ZxQn8HVmXsY.mkv
