wget https://s3.amazonaws.com/ava-dataset/trainval/aMYcLyh9OhU.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/aRbLw-dU2XY.mp4
wget https://s3.amazonaws.com/ava-dataset/trainval/b5pRYl_djbs.mp4
wget https://s3.amazonaws.com/ava-dataset/trainval/BCiuXAuCKAU.mp4
wget https://s3.amazonaws.com/ava-dataset/trainval/BY3sZmvUp-0.mp4
wget https://s3.amazonaws.com/ava-dataset/trainval/C3qk4yAMANk.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/CG98XdYsgrA.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/CrlfWnsS7ac.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/D-BJTU6NxZ8.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/dgLApPvmfBE.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/_eBah6c5kyA.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/Ekwy7wzLfjc.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/F3dPH6Xqf5M.mp4
wget https://s3.amazonaws.com/ava-dataset/trainval/g1wyIcLPbq0.mp4
wget https://s3.amazonaws.com/ava-dataset/trainval/G5Yr20A5z_Q.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/Gfdg_GcaNe8.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/gjdgj04FzR0.mp4
wget https://s3.amazonaws.com/ava-dataset/trainval/gqmmpoO1JrY.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/Gvp-cj3bmIY.webm
wget https://s3.amazonaws.com/ava-dataset/trainval/HVAmkvLrthQ.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/j35JnR0Q7Es.mp4
wget https://s3.amazonaws.com/ava-dataset/trainval/kMy-6RtoOVU.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/KWoSGtglCms.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/l2XO3tQk8lI.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/lDmLcWWBp1E.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/Lg1jOu8cUBM.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/o4xQ-BEa3Ss.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/oITFHwzfw_k.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/LIavUJVrXaI.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/l-jxh8gpxuY.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/LrDT25hmApw.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/lT1zdTL-3SM.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/lWXhqIAvarw.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/M6cgEs9JgDo.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/oWhvucAskhk.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/qBUu7cy-5Iw.mp4
wget https://s3.amazonaws.com/ava-dataset/trainval/QCLQYnt3aMo.webm
wget https://s3.amazonaws.com/ava-dataset/trainval/qsTqtWVVSLM.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/qx2vAO5ofmo.mp4
wget https://s3.amazonaws.com/ava-dataset/trainval/rCb9-U4TArw.mp4
wget https://s3.amazonaws.com/ava-dataset/trainval/rUYsoIIE37A.mp4
wget https://s3.amazonaws.com/ava-dataset/trainval/rXFlJbXyZyc.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/SHBMiL5f_3Q.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/tjqCzVjojCo.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/TM5MPJIq1Is.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/tNpZtigMc4g.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/tt0t_a1EDCE.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/TzaVHtLXOzY.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/u1ltv6r14KQ.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/UgZFdrNT6W0.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/UIy730JrFIc.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/uNT6HrrnqPU.webm
wget https://s3.amazonaws.com/ava-dataset/trainval/UOfuzrwkclM.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/UOyyTUX5Vo4.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/uPJPNPbWMFk.mp4
wget https://s3.amazonaws.com/ava-dataset/trainval/uq_HBsvP548.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/UrsCy6qIGoo.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/UsLnxI_zGpY.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/uwW0ejeosmk.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/U_WzY2k8IBM.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/uzPI7FcF79U.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/v0L-WkMO3s4.mp4
wget https://s3.amazonaws.com/ava-dataset/trainval/vBbjA4tWCPg.mp4
wget https://s3.amazonaws.com/ava-dataset/trainval/vfjywN5CN0Y.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/Vmef_8MY46w.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/VMNmRlhFT-o.mp4
wget https://s3.amazonaws.com/ava-dataset/trainval/VRlpH1MbWUw.mp4
wget https://s3.amazonaws.com/ava-dataset/trainval/VsYPP2I0aUQ.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/wEAeql4z1O0.mp4
wget https://s3.amazonaws.com/ava-dataset/trainval/wfEOx36N4jA.mp4
wget https://s3.amazonaws.com/ava-dataset/trainval/WKqbLbU68wU.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/WlgxRNCHQzw.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/wogRuPNBUi8.mp4
wget https://s3.amazonaws.com/ava-dataset/trainval/wONG7Vh87B4.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/WSPvfxtqisg.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/WVde9pyaHg4.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/X5wWhZ2r9kc.mp4
wget https://s3.amazonaws.com/ava-dataset/trainval/x-6CtPWVi6E.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/xeGWXqSvC-8.webm
wget https://s3.amazonaws.com/ava-dataset/trainval/XF87VL5T0aA.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/XglAvHaEtHY.mp4
wget https://s3.amazonaws.com/ava-dataset/trainval/xJmRNZVDDCY.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/xmqSaQPzL1E.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/xO4ABy2iOQA.mp4
wget https://s3.amazonaws.com/ava-dataset/trainval/xp67EC-Hvwk.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/XpGRS72ghag.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/-XpUuIgyUHE.mp4
wget https://s3.amazonaws.com/ava-dataset/trainval/XV_FF3WC7kA.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/y7ncweROe9U.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/yMtGmGa8KZ0.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/yn9WN9lsHRE.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/yo-Kg2YxlZs.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/yqImJuC5UzI.mp4
wget https://s3.amazonaws.com/ava-dataset/trainval/Ytga8ciKWJc.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/yvgCGJ6vfkY.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/YYWdB7h1INo.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/Z1YV6wB037M.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/z3kgrh0L_80.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/_-Z6wFjXtGQ.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/zC5Fh2tTS1U.mp4
wget https://s3.amazonaws.com/ava-dataset/trainval/-ZFgsrolSxo.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/z-fsLpGHq6o.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/zG7mx8KiavA.mp4
wget https://s3.amazonaws.com/ava-dataset/trainval/zlVkeKC6Ha8.mp4
wget https://s3.amazonaws.com/ava-dataset/trainval/ZosVdkY76FU.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/zR725veL-DI.mkv
wget https://s3.amazonaws.com/ava-dataset/trainval/ZxQn8HVmXsY.mkv
