wget https://s3.amazonaws.com/ava-dataset/test/aDfOtlsdoWw.mkv
wget https://s3.amazonaws.com/ava-dataset/test/bNP8Q_8u89A.webm
wget https://s3.amazonaws.com/ava-dataset/test/bUVls-bf0jM.mkv
wget https://s3.amazonaws.com/ava-dataset/test/bzGQK5lH-RA.mkv
wget https://s3.amazonaws.com/ava-dataset/test/c5mlhcFYYZs.mp4
wget https://s3.amazonaws.com/ava-dataset/test/cYt6NaQgcEk.mp4
wget https://s3.amazonaws.com/ava-dataset/test/cqkChR44vkA.mkv
wget https://s3.amazonaws.com/ava-dataset/test/fT_WjgJ_-r0.mkv
wget https://s3.amazonaws.com/ava-dataset/test/gEI9qBdVt5I.mp4
wget https://s3.amazonaws.com/ava-dataset/test/h7Atb503JwY.webm
wget https://s3.amazonaws.com/ava-dataset/test/hgmK4Epb02E.mkv
wget https://s3.amazonaws.com/ava-dataset/test/i9cuy3teV0w.mkv
wget https://s3.amazonaws.com/ava-dataset/test/ipBRBABLSAk.mkv
wget https://s3.amazonaws.com/ava-dataset/test/jKKXDh4lYd0.mkv
wget https://s3.amazonaws.com/ava-dataset/test/kW5WyJ1QNpM.mkv
wget https://s3.amazonaws.com/ava-dataset/test/keUOiCcHtoQ.mkv
wget https://s3.amazonaws.com/ava-dataset/test/kvFlbTK812w.mkv
wget https://s3.amazonaws.com/ava-dataset/test/l8_Mk3-sZsQ.mkv
wget https://s3.amazonaws.com/ava-dataset/test/nAg_NVzLoAY.mkv
wget https://s3.amazonaws.com/ava-dataset/test/nRzhjXMIXt4.mkv