wget https://s3.amazonaws.com/ava-dataset/test/Ic0LMbDyc9Y.mkv
wget https://s3.amazonaws.com/ava-dataset/test/JiBiCiK9HjY.mp4
wget https://s3.amazonaws.com/ava-dataset/test/K-tICG1ek-E.mp4
wget https://s3.amazonaws.com/ava-dataset/test/Ke8b1_yiUVQ.mkv
wget https://s3.amazonaws.com/ava-dataset/test/KkAf75yOKqs.mkv
wget https://s3.amazonaws.com/ava-dataset/test/KrMSZUQJlNM.mkv
wget https://s3.amazonaws.com/ava-dataset/test/LO964EmiVfo.mkv
wget https://s3.amazonaws.com/ava-dataset/test/Mz0FKktvMLY.mkv
wget https://s3.amazonaws.com/ava-dataset/test/NUwem2aZa0Y.mp4
wget https://s3.amazonaws.com/ava-dataset/test/O5y8zKl9X2E.mp4
wget https://s3.amazonaws.com/ava-dataset/test/O8xkUcUJPNo.mkv
wget https://s3.amazonaws.com/ava-dataset/test/OEUMcSba9t0.mp4
wget https://s3.amazonaws.com/ava-dataset/test/OL_Wwo5W1Zs.mp4
wget https://s3.amazonaws.com/ava-dataset/test/OQxN4ksema0.mkv
wget https://s3.amazonaws.com/ava-dataset/test/P5EhajqkqPw.mkv
wget https://s3.amazonaws.com/ava-dataset/test/QTf_v67C5KI.mp4
wget https://s3.amazonaws.com/ava-dataset/test/Qes4a8HuyEc.mkv
wget https://s3.amazonaws.com/ava-dataset/test/RCNuAys0Hsg.mkv
wget https://s3.amazonaws.com/ava-dataset/test/RW-H3fN_79I.mp4
wget https://s3.amazonaws.com/ava-dataset/test/Scg5LeZszCc.mkv