wget https://s3.amazonaws.com/ava-dataset/test/Sntyb4omSfU.mkv
wget https://s3.amazonaws.com/ava-dataset/test/SoNhz0WJZsI.mkv
wget https://s3.amazonaws.com/ava-dataset/test/Uw7387tc9PU.mp4
wget https://s3.amazonaws.com/ava-dataset/test/V6RX59GT-3k.mkv
wget https://s3.amazonaws.com/ava-dataset/test/VNZ8JDb8sks.mkv
wget https://s3.amazonaws.com/ava-dataset/test/ViY7CR2TSO8.mkv
wget https://s3.amazonaws.com/ava-dataset/test/W8TFzEy0gp0.mkv
wget https://s3.amazonaws.com/ava-dataset/test/WMFTBgYWJS8.mkv
wget https://s3.amazonaws.com/ava-dataset/test/Wgytpy6TeUA.mp4
wget https://s3.amazonaws.com/ava-dataset/test/WhkON_S-pQc.mp4
wget https://s3.amazonaws.com/ava-dataset/test/XOe9GeojzCs.mp4
wget https://s3.amazonaws.com/ava-dataset/test/YAAUPjq-L-Q.mp4
wget https://s3.amazonaws.com/ava-dataset/test/Z0FEElATNjk.mkv
wget https://s3.amazonaws.com/ava-dataset/test/Z42lnoj2n08.mkv
wget https://s3.amazonaws.com/ava-dataset/test/ZS2C28fDC9U.mp4
wget https://s3.amazonaws.com/ava-dataset/test/ZbeMNLwASVo.mkv
wget https://s3.amazonaws.com/ava-dataset/test/ZsgPK0XGYoM.mp4
wget https://s3.amazonaws.com/ava-dataset/test/Zu4iQJrlpo0.mkv
wget https://s3.amazonaws.com/ava-dataset/test/_kbrVsCaaPo.mp4
wget https://s3.amazonaws.com/ava-dataset/test/_vy57h5Oeys.mkv