wget https://s3.amazonaws.com/ava-dataset/test/BD3zaLKhkV4.mkv
wget https://s3.amazonaws.com/ava-dataset/test/BLDTynQwGRI.mkv
wget https://s3.amazonaws.com/ava-dataset/test/BU98nWUtT5E.mkv
wget https://s3.amazonaws.com/ava-dataset/test/BV1VreCWZ64.mkv
wget https://s3.amazonaws.com/ava-dataset/test/BnIFkfDhJ2w.mkv
wget https://s3.amazonaws.com/ava-dataset/test/DaUzhc9_6io.mp4
wget https://s3.amazonaws.com/ava-dataset/test/E-6ruyZFfZs.mkv
wget https://s3.amazonaws.com/ava-dataset/test/E-fqjlYMFhE.mp4
wget https://s3.amazonaws.com/ava-dataset/test/EHMP5-9KUdI.mp4
wget https://s3.amazonaws.com/ava-dataset/test/EO1gLAoEZRA.mp4
wget https://s3.amazonaws.com/ava-dataset/test/FONjBIXaM-0.mp4
wget https://s3.amazonaws.com/ava-dataset/test/G0gDuIVKiXg.mkv
wget https://s3.amazonaws.com/ava-dataset/test/GElolK2jG50.mkv
wget https://s3.amazonaws.com/ava-dataset/test/GQxKfbvL3mg.mkv
wget https://s3.amazonaws.com/ava-dataset/test/Gsm_ZBStr0s.mp4
wget https://s3.amazonaws.com/ava-dataset/test/HPd4eMvs1Kg.mp4
wget https://s3.amazonaws.com/ava-dataset/test/HeKz7BELAQc.mkv
wget https://s3.amazonaws.com/ava-dataset/test/HtXWX0LnifY.mp4
wget https://s3.amazonaws.com/ava-dataset/test/IC5M1EhJNfI.webm
wget https://s3.amazonaws.com/ava-dataset/test/IIyYHprTP58.webm