wget https://s3.amazonaws.com/ava-dataset/test/tj-VmrMYtUI.mp4
wget https://s3.amazonaws.com/ava-dataset/test/u97DLHpcw7c.mkv
wget https://s3.amazonaws.com/ava-dataset/test/vL7N_xRJKJU.mp4
wget https://s3.amazonaws.com/ava-dataset/test/vsMgg4snZzM.mkv
wget https://s3.amazonaws.com/ava-dataset/test/w-jIrlwuv2Y.mkv
wget https://s3.amazonaws.com/ava-dataset/test/wamBSoyRtbs.mkv
wget https://s3.amazonaws.com/ava-dataset/test/woC9Vfbn74I.mkv
wget https://s3.amazonaws.com/ava-dataset/test/xH1WLtZ8csM.mp4
wget https://s3.amazonaws.com/ava-dataset/test/xJpDPrwLJh4.mkv
wget https://s3.amazonaws.com/ava-dataset/test/xT2ogY6xEsI.mp4
wget https://s3.amazonaws.com/ava-dataset/test/o-ZcbjLBtls.mkv
wget https://s3.amazonaws.com/ava-dataset/test/ohn_RxyaCy4.mp4
wget https://s3.amazonaws.com/ava-dataset/test/pSE4Dlork1Y.mp4
wget https://s3.amazonaws.com/ava-dataset/test/pSdPmmJ3-ng.mp4
wget https://s3.amazonaws.com/ava-dataset/test/rJibAAUEMDY.mkv
wget https://s3.amazonaws.com/ava-dataset/test/rRL0Ce8e-RY.mkv
wget https://s3.amazonaws.com/ava-dataset/test/rTCch_5JlkA.mp4
wget https://s3.amazonaws.com/ava-dataset/test/s2z5UASlrP8.mkv
wget https://s3.amazonaws.com/ava-dataset/test/sV3zZROy0uc.mkv
wget https://s3.amazonaws.com/ava-dataset/test/tDF-BqFfF78.mkv